### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lwindsy** [Lwindsy/simpleCompiler#2]
##  todo list
 - [ ] ***error_check function in Syntax Analyzer***
 - [ ] ***visualize the LR_1 Analyzing process by python***
 - [x] ***annotation detecting***
 - [x] ***adjust the syntactic_grammar to adopt latest updates***
